### ISSUE TITLE
Compling Issue Crypto.Util.number

### ISSUE THREAD

**Issue by s1st3r** [AlessandroZ/LaZagne#106]
Amazing project. 

Currently some AV are picking it as virus, so i wonna compile, but everytime i do, i get a 9 MB file which doesn't execute. When i run py lazagne.py --version  , am getting this error

Traceback (most recent call last):
  File "lazagne.py", line 20, in <module>
    from lazagne.softwares.browsers.mozilla import Mozilla
  File "C:\DevWork\LaZagne-master\Windows\lazagne\softwares\browsers\mozilla.p
, line 21, in <module>
    from Crypto.Util.number import long_to_bytes
ImportError: No module named Crypto.Util.number

Anyone experienced this?

**Comment by s1st3r** [comment]
Guys, I have struggled for a while, i figured i to remove pycrypto since i installed with pip, and after removing am supposed to reinstall it with easy_install pycrypto. After that it requested for psutil which i have installed with pip install psutil.

After that i tried to run lazagne.py and this is what i get
py lazagne.py all

########## User: Administrator ##########


[+] 0 passwords have been found.
For more information launch it again with the -v option

So i have decide to compile, and run the tool but check what comes out:


laZagne.exe all

Traceback (most recent call last):
  File "laZagne.py", line 20, in <module>
  File "C:\DevWork\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py"
, line 389, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\browsers\mozilla.py", line 22, in <module>
  File "C:\DevWork\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py"
, line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\Crypto\Cipher\DES3.py", line 67, in <module>
  File "C:\DevWork\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py"
, line 389, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\Crypto\Cipher\_DES3.py", line 7, in <module>
  File "build\bdist.win32\egg\Crypto\Cipher\_DES3.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.
Failed to execute script laZagne

PLEASE HELP

**Comment by AlessandroZ** [comment]
If you have installed all requirements specified on the wiki (https://github.com/AlessandroZ/LaZagne/wiki/Requirements), and you follow the exact process to compile the project (https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile), and it still doesn't work. There is a problem. 

I often had this error when the computer didn't have installed the windows redistributable package so that why for the compile version I embedded the missing dlls. Sometimes this error is still occurring.

So I think, this errors occurs not on the same computer you have compiled it. You should find a way to embed these dlls if my method does not work.

**Comment by s1st3r** [comment]
Hi. Thanks for the reply.

I tried all you said entirely  and i have even tried to recompile it in a new system. I even thought it was a remove and reinstall Microsoft Visual C++ 2010 X86 redistributable

Every time i compile the code, after requirement and coping the DLL from system32, this is the error i get from the executable

`C:\Python27>C:\Python27\dist\laZagne.exe all
Traceback (most recent call last):
  File "laZagne.py", line 20, in <module>
  File "C:\PyInstaller-3.2.1\PyInstaller\loader\pyimod03_importers.py", line 389
, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\browsers\mozilla.py", line 22, in <module>
  File "C:\PyInstaller-3.2.1\PyInstaller\loader\pyimod03_importers.py", line 389
, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\Crypto\Cipher\DES3.py", line 67, in <module>
  File "C:\PyInstaller-3.2.1\PyInstaller\loader\pyimod03_importers.py", line 389
, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\Crypto\Cipher\_DES3.py", line 7, in <module>
  File "build\bdist.win32\egg\Crypto\Cipher\_DES3.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.
Failed to execute script laZagne`

kindly please check that error

**Comment by AlessandroZ** [comment]
I had this error many times (not on my computer, but reported as an issue). See the following issue, it could help you: https://github.com/AlessandroZ/LaZagne/issues/60

Or try older release, it could work as well: https://github.com/AlessandroZ/LaZagne/releases

**Comment by s1st3r** [comment]
AlessandroZ, thank you sir.

Lemmie try out, BRB

**Comment by konstantin42127** [comment]
I have exactly the same error

**Comment by konstantin42127** [comment]
@s1st3r , Have you solved this problem? if so, please be kind, tell me how you decided it
