### ISSUE TITLE
how to compile lazagne windows on linux?

### ISSUE THREAD

**Issue by gearcapitan** [AlessandroZ/LaZagne#143]
┌─[root@Gear] - [~/.wine/drive_c/Python27] - [mar ago 22, 15:36]
└─[$] <> wine ~/.wine/drive_c/Python27/Scripts/pyinstaller.exe --onefile /root/LaZagne/Windows/laZagne.py 
494 INFO: PyInstaller: 3.2.1
498 INFO: Python: 2.7.10
501 INFO: Platform: Windows-2003Server-5.2.3790-SP2
513 INFO: wrote C:\Python27\laZagne.spec
526 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 162, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '\root\LaZagne\Windows\laZagne.py' not found

**Comment by AlessandroZ** [comment]
Sorry I cannot help you, I have never tried to compile it on Linux. However, it should work, so I'm sure you will find a working solution.
