### ISSUE TITLE
didnt working

### ISSUE THREAD

**Issue by hubsternonangry** [AlessandroZ/LaZagne#153]
```
D:\001\laZagne.exe browsers
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
Traceback (most recent call last):
  File "laZagne.py", line 390, in <module>
  File "laZagne.py", line 239, in runLaZagne
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
Failed to execute script laZagne

```

Trying to execute standalone version. 
Win 10, x64, Russian. Antivirus is off, few reboots ago.

**Comment by hubsternonangry** [comment]
And, I didnt have any pyton installer or pyton compiler. Any pyton program. Is this standalone exe independed from any dll's or something else?

**Comment by AlessandroZ** [comment]
I have resolved the problem and pushed the code on github. However, I didn't build the exe yet. I have done some test using russian chars and it worked. 
The correction should be present on the [version 2.3](https://github.com/AlessandroZ/LaZagne/blob/master/CHANGELOG#L3).
