### ISSUE TITLE
error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by mapagm** [AlessandroZ/LaZagne#170]
I have 2 machines - both on Windows 7. LaZagne works well on one of them, on another after "laZagne.exe all" command shows this:
```
Traceback (most recent call last):
  File "laZagne.py", line 127, in launch_module
  File "lazagne\softwares\windows\lsa_secrets.py", line 68, in run
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 171, in get_file_secrets
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 136, in get_secrets
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in get_bootkey
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 94, in find_control_set
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 38, in open_key
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 47, in subkeys
  File "lazagne\softwares\windows\creddump7\newobj.py", line 109, in __div__
  File "lazagne\softwares\windows\creddump7\newobj.py", line 210, in __init__
  File "lazagne\softwares\windows\creddump7\object.py", line 70, in read_value
error: unpack requires a string argument of length 4
Traceback (most recent call last):
  File "laZagne.py", line 127, in launch_module
  File "lazagne\softwares\windows\cachedump.py", line 66, in run
  File "lazagne\softwares\windows\creddump7\win32\domcachedump.py", line 134, in dump_file_hashes
  File "lazagne\softwares\windows\creddump7\win32\domcachedump.py", line 82, in dump_hashes
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in get_bootkey
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 94, in find_control_set
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 38, in open_key
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 47, in subkeys
  File "lazagne\softwares\windows\creddump7\newobj.py", line 109, in __div__
  File "lazagne\softwares\windows\creddump7\newobj.py", line 210, in __init__
  File "lazagne\softwares\windows\creddump7\object.py", line 70, in read_value
error: unpack requires a string argument of length 4
Traceback (most recent call last):
  File "laZagne.py", line 127, in launch_module
  File "lazagne\softwares\windows\hashdump.py", line 52, in run
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 236, in dump_file_hashes
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 223, in dump_hashes
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in get_bootkey
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 94, in find_control_set
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 38, in open_key
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 47, in subkeys
  File "lazagne\softwares\windows\creddump7\newobj.py", line 109, in __div__
  File "lazagne\softwares\windows\creddump7\newobj.py", line 210, in __init__
  File "lazagne\softwares\windows\creddump7\object.py", line 70, in read_value
error: unpack requires a string argument of length 4
```
Am I doing something wrong?

**Comment by AlessandroZ** [comment]
I have no idea, sorry ...  Run it again or try to launch it with admin rights (creddump needs admin rights).
