### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by konstantin42127** [AlessandroZ/LaZagne#178]
I compiled the script with pyinstaller, but when I run an exe file, I get this error

C:\Users\lik47\Desktop\LaZagne-master\Windows\dist>laZagne.exe
Traceback (most recent call last):
  File "laZagne.py", line 4, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\browsers\mozilla.py", line 13, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\Crypto\Cipher\DES3.py", line 67, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "build\bdist.win32\egg\Crypto\Cipher\_DES3.py", line 7, in <module>
  File "build\bdist.win32\egg\Crypto\Cipher\_DES3.py", line 6, in __bootstrap__
ImportError: DLL load failed: ═х эрщфхэ єърчрээ√щ ьюфєы№.
[1184] Failed to execute script laZagne

ran on windows 10 x64
please, help

**Comment by AlessandroZ** [comment]
Try to follow the wiki: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile
I cannot help you a lot, these issue are related to some dependencies missing.

**Comment by konstantin42127** [comment]
AlessandroZ , all dependencies are set, and this error is displayed only when compiled with pyinstaller
