### ISSUE TITLE
Environment Variables Attribute Error

### ISSUE THREAD

**Issue by kenetik** [AlessandroZ/LaZagne#18]
When running the following command: `$ ./LaZagne-64bits all` under the 'Environnement variables passwords' the following error is presented

    Traceback (most recent call last):
      File "<string>", line 183, in <module>
      File "<string>", line 111, in runAllModules
      File "<string>", line 76, in launch_module
      File "/home/joe/Desktop/build/LaZagne/out00-PYZ.pyz/softwares.browsers.opera", line 41, in run
      File "/home/joe/Desktop/build/LaZagne/out00-PYZ.pyz/softwares.browsers.opera", line 61, in decipher_old_version
    AttributeError: 'NoneType' object has no attribute 'warn'

Also, 'Environnement' should be 'Environment'.

**Comment by AlessandroZ** [comment]
This error has been corrected on the last version. Could you please try again. Thank you.

**Comment by kenetik** [comment]
@AlessandroZ +1 I can confirm the issue is now resolved! Thank you.
