### ISSUE TITLE
SubstrateUnderrunError: 94-octet short

### ISSUE THREAD

**Issue by netllama** [AlessandroZ/LaZagne#194]
```
$ ./laZagne.py browsers

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

https://www.thebruerystore.com/signin.aspx XXX@gmail.com ...
https://myaccount.nytimes.com/register XXX@linux-sxs.org 
------------------- Chrome passwords -----------------

Password found !!!
URL: https://www.thebruerystore.com/signin.aspx
Login: XXX@gmail.com
Password: ...

Password found !!!
URL: https://myaccount.nytimes.com/register
Login: XXX@linux-sxs.org
Password: 

Traceback (most recent call last):
  File "./laZagne.py", line 146, in launch_module
    pwdFound = module[i].run(i.capitalize())	# run the module
  File "/home/netllama/stuff/LaZagne/Linux/lazagne/softwares/browsers/mozilla.py", line 501, in run
    loginASN1 = decoder.decode(b64decode(user))
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1049, in __call__
    raise error.SubstrateUnderrunError('%d-octet short' % (length - len(substrate)))
SubstrateUnderrunError: 94-octet short


[+] 2 passwords have been found.
For more information launch it again with the -v option


elapsed time = 0.0855128765106
```

**Comment by netllama** [comment]
seems that its failing on Firefox specifically:
```
------------------- Firefox passwords -----------------

Profile path found: /home/netllama/.mozilla/firefox/3ceo1ujt.default

key: '\x1c&^\xf2\xae#\xdfL\xc7\xfd\xe5\xdc\x9e;\xba\xd0\x02L\x1a\x8c\x16\x13\xe3\xe5'

Traceback (most recent call last):
  File "./laZagne.py", line 146, in launch_module
    pwdFound = module[i].run(i.capitalize())	# run the module
  File "/home/netllama/stuff/LaZagne/Linux/lazagne/softwares/browsers/mozilla.py", line 501, in run
    loginASN1 = decoder.decode(b64decode(user))
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1049, in __call__
    raise error.SubstrateUnderrunError('%d-octet short' % (length - len(substrate)))
SubstrateUnderrunError: 94-octet short
```

**Comment by AlessandroZ** [comment]
I never had this error. I put a try except. Hope it will correct it.

**Comment by netllama** [comment]
Thanks, your change does avoid the crash, and now the errors are reported instead:
```
An error occured decrypting the password: 94-octet short

An error occured decrypting the password: 55-octet short

An error occured decrypting the password: 94-octet short

An error occured decrypting the password: 85-octet short

An error occured decrypting the password: Short octet stream on tag decoding

An error occured decrypting the password: Short octet stream on tag decoding
```
