### ISSUE TITLE
error when i try to run laZagne.exe after compiling it

### ISSUE THREAD

**Issue by someMan0075123** [AlessandroZ/LaZagne#205]
Traceback (most recent call last):
  File "laZagne.py", line 12, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\browsers\mozilla.py", line 14, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 396, in load_module
    exec(bytecode, module.__dict__)
  File "c:\users\user\appdata\local\temp\easy_install-7vig6z\pycrypto-2.6-py2.7-
win-amd64.egg.tmp\Crypto\Cipher\DES3.py", line 67, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 396, in load_module
    exec(bytecode, module.__dict__)
  File "c:\users\user\appdata\local\temp\easy_install-7vig6z\pycrypto-2.6-py2.7-
win-amd64.egg.tmp\Crypto\Cipher\_DES3.py", line 7, in <module>
  File "c:\users\user\appdata\local\temp\easy_install-7vig6z\pycrypto-2.6-py2.7-
win-amd64.egg.tmp\Crypto\Cipher\_DES3.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.
[1956] Failed to execute script laZagne

tested on windows 7 x64

**Comment by KiUserExceptionDispatcher** [comment]
Try to reinstall pycrypto.

**Comment by someMan0075123** [comment]
i already did

**Comment by m41nt41n3r** [comment]
pip install construct

**Comment by aldorm** [comment]
I recommende the next command:
pip install construct==2.5.5-reupload

**Comment by someMan0075123** [comment]
Thank you very much it fixed the problem 👍
