### ISSUE TITLE
ImportError: No module named header

### ISSUE THREAD

**Issue by j3ssie** [AlessandroZ/LaZagne#219]
I get this error when I run laZagne on Kali and Ubuntu.
I also install all from this https://github.com/AlessandroZ/LaZagne/wiki/Requirements but still get this error.
```
Traceback (most recent call last):
  File "./laZagne.py", line 13, in <module>
    from lazagne.config.manageModules import get_categories, get_modules
  File "/root/pentest/LaZagne/Linux/lazagne/config/manageModules.py", line 28, in <module>
    from lazagne.softwares.databases.squirrel import Squirrel
  File "/root/pentest/LaZagne/Linux/lazagne/softwares/databases/squirrel.py", line 5, in <module>
    from lazagne.config.header import Header
ImportError: No module named header

```

**Comment by AlessandroZ** [comment]
Should be fixed now. Thanks for your feedback
