### ISSUE TITLE
Python error on Windows

### ISSUE THREAD

**Issue by tyranonerd** [AlessandroZ/LaZagne#22]
Hi, the last standalone windows exe seems to be broken. I've got this error:

Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Users\John\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_importers.py", line 518, in install
  File "C:\Users\John\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_importers.py", line 162, in __init__
ImportError: Can't load frozen modules.

**Comment by AlessandroZ** [comment]
Could you please refer to the #23 issue and answer to these question. Thank you.
