### ISSUE TITLE
Issue with new DPAPI

### ISSUE THREAD

**Issue by alxchk** [AlessandroZ/LaZagne#221]
Hi, I tried last master and got this issue:

```------------------- Creds_files -------------------

[-] Creds_files: Traceback (most recent call last):
  File "laZagne.py", line 98, in run_module
  File "lazagne/softwares/windows/creds_files.py", line 19, in run
  File "lazagne/config/dpapi_structure.py", line 92, in decrypt_cred
  File "lazagne/config/DPAPI/credfile.py", line 23, in decrypt
  File "lazagne/config/DPAPI/blob.py", line 60, in decrypt_encrypted_blob
  File "lazagne/config/DPAPI/masterkey.py", line 180, in get_master_keys
TypeError: list indices must be integers, not str
```

I'm not sure, but likely this should looks like this:
```
-               return self.keys.get(guid, [])['keys']
+               return self.keys.get(guid, {}).get('keys')
```

**Comment by AlessandroZ** [comment]
Thank you, it has been fixed now. You were right about your correction :)
