### ISSUE TITLE
DPAPI... 

### ISSUE THREAD

**Issue by jun0s** [AlessandroZ/LaZagne#222]
Well, this happen in windows 10...

Traceback (most recent call last):
  File "laZagne.py", line 443, in <module>
    for r in runLaZagne(category_choosed):
  File "laZagne.py", line 278, in runLaZagne
    for r in runModule(category_choosed):
  File "laZagne.py", line 175, in runModule
    constant.dpapi.check_credentials(constant.passwordFound)
  File "E:\LaZagne\Windows\lazagne\config\dpapi_structure.py", line 67, in check_credentials
    for r in self.umkp.try_credential(sid=self.sid, password=password):
  File "E:\LaZagne\Windows\lazagne\config\DPAPI\masterkey.py", line 260, in try_credential
    mk.decrypt_with_password(sid, password)
  File "E:\LaZagne\Windows\lazagne\config\DPAPI\masterkey.py", line 44, in decrypt_with_password
    self.decrypt_with_hash(sid=sid, pwdhash=hashlib.new(algo, pwd.encode("UTF-16LE")).digest())
AttributeError: 'bool' object has no attribute 'encode'

thank you, very good work.

**Comment by AlessandroZ** [comment]
Thanks, it fixed now
