### ISSUE TITLE
last standalone windows exe problem

### ISSUE THREAD

**Issue by savsay** [AlessandroZ/LaZagne#23]
Hi, the last standalone windows exe seems to be broken. I've got this error:
Traceback (most recent call last):
  File "<string>", line 182, in <module>
  File "<string>", line 110, in runAllModules
  File "<string>", line 75, in launch_module
  File "C:\Users\John\Desktop\LaZagne\build\laZagne\out00-PYZ.pyz\softwares.win
ows.network", line 102, in run
  File "C:\Users\John\Desktop\LaZagne\build\laZagne\out00-PYZ.pyz\config.write_
utput", line 98, in print_output
  File "C:\Users\111\AppData\Local\Temp\_MEI97162\eggs\colorama-0.3.3-py2.7.egg
colorama\ansitowin32.py", line 36, in write
  File "C:\Users\111\AppData\Local\Temp\_MEI97162\eggs\colorama-0.3.3-py2.7.egg
colorama\ansitowin32.py", line 133, in write
  File "C:\Users\111\AppData\Local\Temp\_MEI97162\eggs\colorama-0.3.3-py2.7.egg
colorama\ansitowin32.py", line 161, in write_and_convert
  File "C:\Users\111\AppData\Local\Temp\_MEI97162\eggs\colorama-0.3.3-py2.7.egg
colorama\ansitowin32.py", line 166, in write_plain_text
  File "C:\Users\John\Desktop\LaZagne\build\laZagne\out00-PYZ.pyz\encodings.cp8
6", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-171:
character maps to <undefined>

**Comment by AlessandroZ** [comment]
Hi, 
I have tried again and it works for me. It could be a problem of pyinstaller. 
Could you please give me more information about your computer: 32 bits / 64 bits - OS (win7/ 8) - if it's a surface or another tablet - etc. 
Some other standalone worked or no ? 
Thank you.

**Comment by tyranonerd** [comment]
Hi, I tried it on a Windows 8.1 64bits desktop computer, I will try old builds this evening

**Comment by void-in** [comment]
Tested on Windows 7 64bit and it is working fine. Will check on Windows 8.1 x64

**Comment by savsay** [comment]
Hi ; Tested windows 7 x64-based pc patch level 321 hotfix installed; Default Language Russian ; installed python default env path python2.7

Still problem have

**Comment by AlessandroZ** [comment]
But you're talking about launching the tool using python or the standalone ? 
If it's the standalone, as you have python installed as well, could you please launch it using the source code (python lazagne.py all) to see if an error occurs (which means that it will be a problem of my code and not pyinstaller). 

Thank you.

**Comment by void-in** [comment]
@savsay I believe this is due to the Russian language issue. The error also indicates unicode problem. 

@AlessandroZ Can you confirm?

**Comment by savsay** [comment]
@AlessandroZ I tried standalone .exe give error i also thinks it's depends Russian Language.

**Comment by markus80** [comment]
btw: John is a nut. ;)
Also occuring on Win7 x64, German

Traceback (most recent call last):
  File "<string>", line 190, in <module>
  File "<string>", line 106, in runModule
  File "<string>", line 75, in launch_module
  File "C:\Users\John\Desktop\src\LaZagne\build\laZagne\out00-PYZ.pyz\softwares.mails.outlook", line
 47, in run
  File "C:\Users\John\Desktop\src\LaZagne\build\laZagne\out00-PYZ.pyz\config.write_output", line 98,
 in print_output
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 36, in write
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 133, in write
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 161, in write_and_convert
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 166, in write_plain_text
  File "C:\Users\John\Desktop\src\LaZagne\build\laZagne\out00-PYZ.pyz\encodings.cp850", line 12, in
encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-25: character maps to <und
efined>

**Comment by 0E800** [comment]
@dev, this might be helpful to correct unicode errors:
http://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters



On Wed, Jun 17, 2015 at 8:57 AM, markus80 <notifications@github.com> wrote:

> btw: John is a nut. ;)
> Also occuring on Win7 x64, German
>
> Traceback (most recent call last):
> File "", line 190, in
> File "", line 106, in runModule
> File "", line 75, in launch_module
> File
> "C:\Users\John\Desktop\src\LaZagne\build\laZagne\out00-PYZ.pyz\softwares.mails.outlook",
> line
> 47, in run
> File
> "C:\Users\John\Desktop\src\LaZagne\build\laZagne\out00-PYZ.pyz\config.write_output",
> line 98,
> in print_output
> File "build\bdist.win32\egg\colorama\ansitowin32.py", line 36, in write
> File "build\bdist.win32\egg\colorama\ansitowin32.py", line 133, in write
> File "build\bdist.win32\egg\colorama\ansitowin32.py", line 161, in
> write_and_convert
> File "build\bdist.win32\egg\colorama\ansitowin32.py", line 166, in
> write_plain_text
> File
> "C:\Users\John\Desktop\src\LaZagne\build\laZagne\out00-PYZ.pyz\encodings.cp850",
> line 12, in
> encode
> UnicodeEncodeError: 'charmap' codec can't encode characters in position
> 7-25: character maps to efined>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/23#issuecomment-112859634>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by AlessandroZ** [comment]
Could you try the version 0.9.1 please.
