### ISSUE TITLE
TypeError exception when running on my laptop

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#231]
After LaZagne prints out passwords it finds and before printing how many total passwords were found and exiting, I see the following exception:

```
Traceback (most recent call last):
  File "laZagne.py", line 99, in run_module
    pwdFound = module.run(title.capitalize())                                   # run the module
  File "C:\Code\Misc\LaZagne\Windows\lazagne\softwares\windows\windows.py", line 61, in run
    password = constant.dpapi.get_cleartext_password()
  File "C:\Code\Misc\LaZagne\Windows\lazagne\config\dpapi_structure.py", line 117, in get_cleartext_password
    return self.umkp.get_cleartext_password()
  File "C:\Code\Misc\LaZagne\Windows\lazagne\config\DPAPI\masterkey.py", line 229, in get_cleartext_password
    return self.get_password(guid)
  File "C:\Code\Misc\LaZagne\Windows\lazagne\config\DPAPI\masterkey.py", line 191, in get_password
    return self.keys.get(guid, [])['password']
TypeError: list indices must be integers, not str
```

EDIT: I ran it with 'all' parameter. Rerun with 'all -v' shows the exception is in the Windows passwords section.

**Comment by eranzim** [comment]
I think there is a double bug there:

1. The line should change from `return self.keys.get(guid, [])['password']` to `return self.keys.get(guid, {}).get('password')` (notice I made 2 changes - both the default value and calling get in case the value doesn't exist)
2. When I ran it, I see one of the keys is `u'0616762b-306f-406b-aeb3-33a927bdec52'`, while the value of guid is `'616762b-306f-406b-aeb3-33a927bdec52'` (notice the extra leading '0')

**Comment by AlessandroZ** [comment]
Should be fixed now. Open the issue again if you still have the issue.
