### ISSUE TITLE
ArgumentError: expected LP_MEMORY_BASIC_INFORMATION instance instead of pointer to MEMORY_BASIC_INFORMATION

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#245]
I'm getting the following error when calling LaZagne from my code. It happens in the 'Windows' category:

```
Traceback (most recent call last):
  File "laZagne.pyo", line 99, in run_module
  File "lazagne\softwares\windows\windows.pyo", line 56, in run
  File "lazagne\softwares\windows\mimikatz.pyo", line 564, in find_wdigest_password
  File "lazagne\softwares\windows\mimikatz.pyo", line 210, in acquire_crypto_material
  File "lazagne\softwares\windows\mimikatz.pyo", line 156, in find_signature
  File "memorpy\MemWorker.pyo", line 189, in mem_search
  File "memorpy\WinProcess.pyo", line 193, in iter_region
  File "memorpy\WinProcess.pyo", line 169, in VirtualQueryEx
ArgumentError: argument 3: <type 'exceptions.TypeError'>: expected LP_MEMORY_BASIC_INFORMATION instance instead of pointer to MEMORY_BASIC_INFORMATION
```

Similarly, on another computer, I got the following:
```
Traceback (most recent call last):
  File "laZagne.pyo", line 99, in run_module
  File "lazagne\softwares\windows\windows.pyo", line 56, in run
  File "lazagne\softwares\windows\mimikatz.pyo", line 558, in find_wdigest_password
  File "memorpy\MemWorker.pyo", line 35, in __init__
  File "memorpy\WinProcess.pyo", line 49, in __init__
  File "memorpy\WinProcess.pyo", line 164, in GetNativeSystemInfo
ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected LP_SYSTEM_INFO instance instead of pointer to SYSTEM_INFO
```

And on a third:
```
Traceback (most recent call last):
  File "laZagne.pyo", line 99, in run_module
  File "lazagne\softwares\windows\windows.pyo", line 56, in run
  File "lazagne\softwares\windows\mimikatz.pyo", line 558, in find_wdigest_password
  File "memorpy\MemWorker.pyo", line 35, in __init__
  File "memorpy\WinProcess.pyo", line 48, in __init__
  File "memorpy\WinProcess.pyo", line 66, in is_64bit
ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_c_long instance instead of pointer to c_bool
```

**Comment by AlessandroZ** [comment]
mimikatz module has been removed and replaced by pypykatz. You should not have this kind of error anymore
