### ISSUE TITLE
WindowsError: [Error 998] Invalid access to memory location  (exception raised in Windows category)

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#250]
Got the following exception in the `Windows` category:
```
Traceback (most recent call last):
  File "laZagne.pyo", line 99, in run_module
  File "lazagne\softwares\windows\windows.pyo", line 56, in run
  File "lazagne\softwares\windows\mimikatz.pyo", line 568, in find_wdigest_password
  File "lazagne\softwares\windows\mimikatz.pyo", line 413, in walk_entries
  File "lazagne\softwares\windows\mimikatz.pyo", line 356, in get_entry_at
  File "lazagne\softwares\windows\mimikatz.pyo", line 82, in get_data
  File "memorpy\Address.pyo", line 46, in read
  File "memorpy\BaseProcess.pyo", line 51, in read
  File "memorpy\WinProcess.pyo", line 261, in read_bytes
WindowsError: [Error 998] Invalid access to memory location.
```

**Comment by AlessandroZ** [comment]
Do you have the exact version of the Windows used ?

**Comment by eranzim** [comment]
Windows 7 enterprise, SP1, x64 (ver 6.1.7601)

**Comment by AlessandroZ** [comment]
as explain, you should not have these kind of errors anymore
