### ISSUE TITLE
Windows 7 x64: NameError: name 'Struct' is not defined

### ISSUE THREAD

**Issue by ScienceDiscoverer** [AlessandroZ/LaZagne#260]
I compiled with latest version of 2.7.15, with all wiki requirements installed. And I get this at execution. Here is full traceback:

```
Traceback (most recent call last):
  File "Windows\laZagne.py", line 27, in <module>
  File "c:\program files\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line
396, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\lazagne\config\manage_modules.py", line 57, in <module>
  File "c:\program files\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line
396, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\lazagne\softwares\windows\windows.py", line 13, in <module>
  File "c:\program files\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line
396, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\lazagne\softwares\windows\mimikatz.py", line 131, in <module>
  File "Windows\lazagne\softwares\windows\mimikatz.py", line 145, in LsaDecryptor
NameError: name 'Struct' is not defined
[9080] Failed to execute script laZagne
```
Here is traceback if I run it from 

> python lazagne.py all

> Traceback (most recent call last):
>   File "scripts\windows\lazagne.py", line 27, in <module>
>     from lazagne.config.manage_modules import get_categories, get_modules
>   File "C:\Program Files\Python27\scripts\windows\lazagne\config\manage_modules.py", line 57, in <mo
> dule>
>     from lazagne.softwares.windows.windows import WindowsPassword
>   File "C:\Program Files\Python27\scripts\windows\lazagne\softwares\windows\windows.py", line 13, in
>  <module>
>     from .mimikatz import Mimikatz
>   File "C:\Program Files\Python27\scripts\windows\lazagne\softwares\windows\mimikatz.py", line 131,
> in <module>
>     class LsaDecryptor():
>   File "C:\Program Files\Python27\scripts\windows\lazagne\softwares\windows\mimikatz.py", line 145,
> in LsaDecryptor
>     HARD_KEY = Struct(
> NameError: name 'Struct' is not defined

**Comment by AlessandroZ** [comment]
Hi, 

Take the last github version (not the last release), I have just done some modification. And be sure to have installed the exact construct [lib](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/requirement.txt#L1). 

Struct is defined in construct.
