### ISSUE TITLE
Hashdump module

### ISSUE THREAD

**Issue by Banaanhangwagen** [AlessandroZ/LaZagne#261]
Latest master; i get this error

------------------- Hashdump passwords -----------------

[!] Traceback (most recent call last):
  File "laZagne.py", line 121, in run_module
    pwd_found = module.run()  # run the module
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\hashdump.py", line 12, in run
    hashdump = dump_file_hashes(constant.hives['system'], constant.hives['sam'])
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 263, in dump_file_hashes
    return dump_hashes(sysaddr, samaddr)
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 250, in dump_hashes
    lmhash, nthash = get_user_hashes(user, hbootkey)
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 226, in get_user_hashes
    return decrypt_hashes(rid, enc_lm_hash, enc_nt_hash, hbootkey)
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 201, in decrypt_hashes
    nthash = decrypt_single_hash(rid, hbootkey, enc_nt_hash, antpassword)
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 178, in decrypt_single_hash
    (des_k1, des_k2) = sid_to_key(rid)
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 93, in sid_to_key
    return str_to_key(s1), str_to_key(s2)
  File "c:\Users\XXX\Documents\LaZagne\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 67, in str_to_key
    key.append(char_to_int(s[0]) >> 1)
NameError: global name 'char_to_int' is not defined

**Comment by AlessandroZ** [comment]
Thanks !

**Comment by Banaanhangwagen** [comment]
Ok, that did the trick.
But...when using latest master now (on latest Win10), the _hashdump_ sections stays empty.  

![image](https://user-images.githubusercontent.com/25983612/44959125-32a42a80-aeea-11e8-8f90-91459c5fe343.png)

**Comment by AlessandroZ** [comment]
Try the new version, it should be fixed
