### ISSUE TITLE
No module named 'd3des'

### ISSUE THREAD

**Issue by jomoza** [AlessandroZ/LaZagne#285]
I do:
```
D:\PENTESTING\LaZagne\Windows>"D:\ProgramData\Python36_64\Scripts\pip.exe"  install pyDes
Requirement already satisfied: pyDes in d:\programdata\python36_64\lib\site-packages (2.0.1)
```
But:
```
D:\PENTESTING\LaZagne\Windows>"D:\ProgramData\Python36_64\python.exe" laZagne.py
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
    from lazagne.config.manage_modules import get_categories
  File "D:\PENTESTING\LaZagne\Windows\lazagne\config\manage_modules.py", line 45, in <module>
    from lazagne.softwares.sysadmin.vnc import Vnc
  File "D:\PENTESTING\LaZagne\Windows\lazagne\softwares\sysadmin\vnc.py", line 3, in <module>
    import d3des as d
ModuleNotFoundError: No module named 'd3des'
```

**Comment by Banaanhangwagen** [comment]
Try running it with python27

**Comment by AlessandroZ** [comment]
@Banaanhangwagen has right, the windows version is not compatible with python 3 yet. 
Python 3 does not like to import files like that, so it crashed even if the file exists: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/sysadmin/d3des.py
