### ISSUE TITLE
Latest lazagne app crash

### ISSUE THREAD

**Issue by alxchk** [AlessandroZ/LaZagne#287]
```
2018-09-25 18:39:46,591|  ------------------- Credfiles passwords --------------
---

[+] Password found !!!
Username: XXXX
Domain: LegacyGeneric:target=XXXXX
Password: YYYYYY
File: C:\Users\ZZZZZ\AppData\Roaming\Microsoft\Credentials\AAAA
BBBBBBB

2018-09-25 18:39:46,591|  ------------------- Vaultfiles passwords -------------
----

2018-09-25 18:39:46,607| [!] No passwords found
2018-09-25 18:39:46,607| [!] Traceback (most recent call last):
  File "lazagne/config/change_privileges.py", line 98, in list_sids
  File "f:a9", line 21, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordin
al not in range(128)

2018-09-25 18:39:46,607| [!] Traceback (most recent call last):
  File "lazagne/config/change_privileges.py", line 98, in list_sids
  File "f:a9", line 21, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordin
al not in range(128)

2018-09-25 18:39:46,607| [!] Traceback (most recent call last):
  File "lazagne/config/change_privileges.py", line 98, in list_sids
  File "f:a9", line 21, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordin
al not in range(128)

2018-09-25 18:39:46,607| [!] Traceback (most recent call last):
  File "lazagne/config/change_privileges.py", line 98, in list_sids
  File "f:a9", line 21, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordin
al not in range(128)

2018-09-25 18:39:46,607| [!] Traceback (most recent call last):
  File "lazagne/config/change_privileges.py", line 98, in list_sids
  File "f:a9", line 21, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordin
al not in range(128)

2018-09-25 18:39:46,607| [!] Traceback (most recent call last):
  File "lazagne/config/change_privileges.py", line 98, in list_sids
  File "f:a9", line 21, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordin
al not in range(128)
```

```
Module: RPCRT4.dll 
Module ver: 6.1.7601.19160
Exception code: c0000005
OS: 6.1.7601.2.1.0.256.48
http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419
```

**Comment by alxchk** [comment]
Looks like crash caused by pypykatz

**Comment by AlessandroZ** [comment]
Hmm it seems to crash [here](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/change_privileges.py#L98).

Could you test removing the `.decode(sys.getfilesystemencoding()` maybe it is not needed for non ascii name. 
The `owner` variable is already retrieved as unicode [here](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/winstructure.py#L439).

I should do more tests with non ascii systems.

**Comment by alxchk** [comment]
I tried this. You using W functions, so no need to decode anything, it's already in uncode. But this doesn't cause issue. Looks like pypykatz corrupt some memory or security context of current process, so it crashes after cleanup. 
Removing Pypykatz from categories resolves issue. I commented all modules one by one >_<

**Comment by AlessandroZ** [comment]
This is weird because I have done some tests on a latin system and it worked. When I see your debug output, I see than credentials files have been decrypted and this is done using the user sha1 hash (retrieved from pypykatz) or because you used the same password stored on another software (as firefox - it tests for password reused). 
CredFiles and VaultFiles modules didn't fail but the crash occurs later. 

So for me it happens trying to list sids. To confirm that you can comment all that code and it should work: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/run.py#L208L243

You can also try to uncomment this [line](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/run.py#L189) and comment the next one (I have changed it some times ago, but could fail on non latin system). 

And if you can give me the output of the crash without the `.decode(sys.getfilesystemencoding()`, it should not be a `UnicodeEncodeError` anymore I think. It should help me. 

Thanks
