### ISSUE TITLE
[5032] Failed to execute script laZagne

### ISSUE THREAD

**Issue by hktalent** [AlessandroZ/LaZagne#295]
c:\>laZagne.exe all
laZagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[5032] Failed to execute script laZagne
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 170, in run_lazagne
  File "lazagne\config\dpapi_structure.py", line 165, in __init__
  File "lazagne\softwares\windows\lsa_secrets.py", line 25, in run
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 185, in get_file_secrets
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 146, in get_secrets
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 112, in get_bootkey
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in find_control_set
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 40, in open_key
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 52, in subkeys
  File "lazagne\softwares\windows\creddump7\newobj.py", line 107, in __getattribute__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by AlessandroZ** [comment]
I cannot reproduce it, which system do you use (XP, win7, win8, etc.), which OS arch (x86, x64) and which process arch ? 
Thanks

**Comment by KiUserExceptionDispatcher** [comment]
> I cannot reproduce it, which system do you use (XP, win7, win8, etc.), which OS arch (x86, x64) and which process arch ?
This information can be added in "BANG BANG" banner, don't you think so?

**Comment by AlessandroZ** [comment]
Yes you're right. Maybe I should add these information and the python version after the banner when running in debug mode. It could be useful to check errors.

**Comment by AlessandroZ** [comment]
Same as #316.
