### ISSUE TITLE
lazagne won't run in meterpreter session

### ISSUE THREAD

**Issue by mapagm** [AlessandroZ/LaZagne#298]
Hi,

I have a machine with Windows 10 x64. Lazagne (lazagne.exe - lastest) runs without any issues when i run it directly on this machine. But when i open meterpreter session (with system rights) and try to run lazagne.exe in shell i get error:

> [9260] Failed to execute script laZagne
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 170, in run_lazagne
  File "lazagne\config\dpapi_structure.py", line 165, in __init__
  File "lazagne\softwares\windows\lsa_secrets.py", line 25, in run
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 179, in get_file_secrets
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 143, in get_secrets
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 112, in get_bootkey
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in find_control_set
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 40, in open_key
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 50, in subkeys
  File "lazagne\softwares\windows\creddump7\newobj.py", line 111, in __div__
  File "lazagne\softwares\windows\creddump7\newobj.py", line 214, in __init__
  File "lazagne\softwares\windows\creddump7\object.py", line 72, in read_value
struct.error: unpack requires a string argument of length 4

It's strange. Any suggestions?

**Comment by AlessandroZ** [comment]
Try to use the same process arch as the system arch (x64 -> x64) or (x86 -> x86).
