### ISSUE TITLE
Fails, "type object 'triple_des' has no attribute 'new'"

### ISSUE THREAD

**Issue by 0x27** [AlessandroZ/LaZagne#306]
Target OS: Windows 10 (Build 14393), x64, German language pack. 

When I execute lazagne (as "system") it crashes with the following:
```
[5796] Failed to execute script laZagne
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 260, in run_lazagne
  File "lazagne\config\run.py", line 125, in run_category
  File "lazagne\config\dpapi_structure.py", line 36, in are_masterkeys_retrieved
  File "lazagne\config\dpapi_structure.py", line 94, in check_credentials
  File "lazagne\config\DPAPI\masterkey.py", line 359, in try_credential
  File "lazagne\config\DPAPI\masterkey.py", line 68, in decrypt_with_password
  File "lazagne\config\DPAPI\masterkey.py", line 55, in decrypt_with_hash
  File "lazagne\config\DPAPI\masterkey.py", line 83, in decrypt_with_key
  File "lazagne\config\DPAPI\crypto.py", line 342, in dataDecrypt
AttributeError: type object 'triple_des' has no attribute 'new'
```

**Comment by KiUserExceptionDispatcher** [comment]
Seems u use outdated version. Show your dataDecrypt routine from lazagne\config\DPAPI\crypto.py.

**Comment by 0x27** [comment]
Was using the current release build - turns out it was possibly user error, I solved it by using the prior release build and ensuring I was using the correct architecture. Or the current release build could be broken (there is not a x64 executable?)

**Comment by AlessandroZ** [comment]
No, the current release build is not up to date, you should use the python code from the github repository and compile it yourself to be up to date. This error has already been corrected.
