### ISSUE TITLE
[8452] Failed to execute script laZagne

### ISSUE THREAD

**Issue by Terik90** [AlessandroZ/LaZagne#309]
latest vesion Lazagne
find some passwords and then:

Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 199, in run_lazagne
  File "lazagne\config\run.py", line 119, in run_category
  File "lazagne\config\dpapi_structure.py", line 36, in are_masterkeys_retrieved

  File "lazagne\config\dpapi_structure.py", line 94, in check_credentials
  File "lazagne\config\DPAPI\masterkey.py", line 359, in try_credential
  File "lazagne\config\DPAPI\masterkey.py", line 68, in decrypt_with_password
  File "lazagne\config\DPAPI\masterkey.py", line 55, in decrypt_with_hash
  File "lazagne\config\DPAPI\masterkey.py", line 83, in decrypt_with_key
  File "lazagne\config\DPAPI\crypto.py", line 342, in dataDecrypt
AttributeError: type object 'triple_des' has no attribute 'new'
[8452] Failed to execute script laZagne

System Windows 7 x64 version 6.1.7601

**Comment by AlessandroZ** [comment]
Hi, you should use the last github version (python code) and not the last release, this error has already been corrected. Thank you.
