### ISSUE TITLE
[5712] Failed to execute script laZagne

### ISSUE THREAD

**Issue by BadFesha** [AlessandroZ/LaZagne#310]
![image](https://user-images.githubusercontent.com/44323960/47258574-5244e180-d49d-11e8-839d-134d54e394c4.png)
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 199, in run_lazagne
  File "lazagne\config\run.py", line 119, in run_category
  File "lazagne\config\dpapi_structure.py", line 36, in are_masterkeys_retrieved
  File "lazagne\config\dpapi_structure.py", line 94, in check_credentials
  File "lazagne\config\DPAPI\masterkey.py", line 362, in try_credential
  File "lazagne\config\DPAPI\credhist.py", line 137, in decrypt_with_password
  File "lazagne\config\DPAPI\credhist.py", line 130, in decrypt_with_hash
  File "lazagne\config\DPAPI\credhist.py", line 79, in decrypt_with_hash
  File "lazagne\config\DPAPI\crypto.py", line 325, in derivePwdHash
TypeError: unsupported operand type(s) for +: 'RPC_SID' and 'str'
[5712] Failed to execute script laZagne

What is the problem?

**Comment by AlessandroZ** [comment]
This error has been corrected on the source code, do not use the last release, it's not up to date. Use the python project.
