### ISSUE TITLE
Failed "laZagne.exe windows" in Windows 10

### ISSUE THREAD

**Issue by hsumerf** [AlessandroZ/LaZagne#318]
I'm using windows 10 64 bit OS with python 2.7.
First I run this command "**laZagne.exe all**" and after chrome password I got error
```
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 199, in run_lazagne
  File "lazagne\config\run.py", line 119, in run_category
  File "lazagne\config\dpapi_structure.py", line 36, in are_masterkeys_retrieved
  File "lazagne\config\dpapi_structure.py", line 94, in check_credentials
  File "lazagne\config\DPAPI\masterkey.py", line 362, in try_credential
  File "lazagne\config\DPAPI\credhist.py", line 137, in decrypt_with_password
  File "lazagne\config\DPAPI\credhist.py", line 130, in decrypt_with_hash
  File "lazagne\config\DPAPI\credhist.py", line 79, in decrypt_with_hash
  File "lazagne\config\DPAPI\crypto.py", line 325, in derivePwdHash
TypeError: unsupported operand type(s) for +: 'RPC_SID' and 'str'
[17584] Failed to execute script laZagne
```
Then I checked All commands and I found that problem is only in "**laZagne.exe windows**" , Now How can we overcome this problem?

**Comment by rmilovidov** [comment]
The same issue on WIN10

**Comment by AlessandroZ** [comment]
This error has been corrected on the source code, do not use the last release, it's not up to date. Use the python project.

**Comment by rmilovidov** [comment]
How to launch the python project file on PC?



>Понедельник, 12 ноября 2018, 19:49 +10:00 от AlessandroZ <notifications@github.com>:
>
>This error has been corrected on the source code, do not use the last release, it's not up to date. Use the python project.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Roman D. Milovidov

**Comment by KoHa-Ta** [comment]
if anyone has this problem just use "-quiet" after "lazagne.exe all"
it helped me.
