### ISSUE TITLE
UnicodeEncodeError: 'charmap' error while searching for Generic Network pw

### ISSUE THREAD

**Issue by Moter8** [AlessandroZ/LaZagne#32]
![0](http://i.imgur.com/JMMOZdy.png)
![1](http://i.imgur.com/hDE87p6.png)

I'm on a Windows 10 Build 9926 x64 system.
Not sure what else I can tell you :/

**Comment by AlessandroZ** [comment]
Hi, 
I could not manage to reproduce the error, however I try to fix it. Could you try again using the last release. Thank you : https://github.com/AlessandroZ/LaZagne/releases/download/0.9/Windows_0.9.zip

**Comment by Moter8** [comment]
@AlessandroZ Hey, now it works, spitting out something that seems to be from Adobe Lightroom.

![1](http://i.imgur.com/ISlZWtE.png)

LaZagne no longer crashes during this :)

**Comment by Moter8** [comment]
```
------------------- Outlook passwords -----------------

Pop3 Password found !!!
POP3 User: [censored]
Traceback (most recent call last):
  File "<string>", line 190, in <module>
  File "<string>", line 116, in runAllModules
  File "<string>", line 75, in launch_module
  File "C:\Users\John\Desktop\LaZagne\build\laZagne\out00-PYZ.pyz\softwares.mail
s.outlook", line 47, in run
  File "C:\Users\John\Desktop\LaZagne\build\laZagne\out00-PYZ.pyz\config.write_o
utput", line 98, in print_output
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 36, in write
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 133, in write
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 161, in write_and_c
onvert
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 166, in write_plain
_text
  File "C:\Users\John\Desktop\LaZagne\build\laZagne\out00-PYZ.pyz\encodings.cp85
0", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-25: ch
aracter maps to <undefined>
```

Heyo, now I'm testing this out on my other PC with outlook installed, and I'm getting this bug again :/

**Comment by AlessandroZ** [comment]
Could you try the version 0.9.1 please.

**Comment by Moter8** [comment]
------------------- Outlook passwords -----------------

Pop3 Password found !!!
POP3 User: [censored]
clsid: õò╗ÒæäÒöÀÒä┤Ô┤▒ÒüéÒÖäÒä¡õÉ▒Ô┤▓õî©õê│ÒÇ¡Òä░ÒÉ░ÒëéÒÖüÒ£Âþ┤Â
POP3 Server: [censored]
SMTP Secure Connection: 0
SMTP Server: [censored]
Mini UID: ÒÉ▒ÒÇ│Òÿ▒Òî▒Òê░
Account Name :[censored]
Display Name: [censored]
POP3 Password: [censored]
Email: [censored]
Leave on Server: ÒöÂÒîÁÒäÂ

Yay, it doesn't crash anymore. The Leave on Server thing is weird though. Mini UID is sometimes a number and sometimes gibberish. CLSID is also gibberish, but I don't know what that is :+1:

**Comment by AlessandroZ** [comment]
Hi,
The pop user and password and the email address are correct or it's written in a non readable format ?
