### ISSUE TITLE
[2556] Failed to execute script laZagne

### ISSUE THREAD

**Issue by QuestYouCraft** [AlessandroZ/LaZagne#352]
Hello, users, I compiled the file, the compilation was successful, however, when I started lazagne.exe, I encountered this error:
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows\dist>lazagne.exe all
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\config\manage_modules.py", line 59, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\windows\ppypykatz.py", line 10, in <module>
ImportError: No module named pypykatz.pypykatz
[2556] Failed to execute script laZagne
```
How to fix this error? Thank you in advance.

**Comment by plonibarploni** [comment]
Do you get the same error when running it directly in python (i.e. not your compiled version)?
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows\>python.exe lazagne.py all
```

**Comment by QuestYouCraft** [comment]
No

**Comment by QuestYouCraft** [comment]
Yes, I do

**Comment by plonibarploni** [comment]
Did you install the dependencies?
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows\>pip install -r requirement.txt
```

**Comment by QuestYouCraft** [comment]
Yes, I do
My file:
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows\dist>lazagne.exe all
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\config\manage_modules.py", line 59, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\windows\ppypykatz.py", line 10, in <module>
ImportError: No module named pypykatz.pypykatz
[2708] Failed to execute script laZagne
```
Python Project:
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows>python.exe lazagne.py all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

########## User: QuestYouCraft ##########

Here my password

[+] 1 passwords have been found.
For more information launch it again with the -v option

elapsed time = 1.95000004768
```

**Comment by QuestYouCraft** [comment]
Yes, I do
My file:
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows\dist>lazagne.exe all
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\config\manage_modules.py", line 59, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\windows\ppypykatz.py", line 10, in <module>
ImportError: No module named pypykatz.pypykatz
[2708] Failed to execute script laZagne
```
Python Project:
```
C:\Users\QuestYouCraft\Desktop\LaZagne-master\Windows>python.exe lazagne.py all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

########## User: QuestYouCraft ##########

Here my password

[+] 1 passwords have been found.
For more information launch it again with the -v option

elapsed time = 1.95000004768
```

**Comment by plonibarploni** [comment]
In order for the exe to work, you will need to recompile it.

**Comment by QuestYouCraft** [comment]
OK
