### ISSUE TITLE
error with admin access

### ISSUE THREAD

**Issue by byehack** [AlessandroZ/LaZagne#362]
i get this error in cmd admin on py36 and win10:

```C:\Users\mohammad      t\Downloads\LaZagne-master\Windows>py lazagne.py all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\newobj.py", line 86, in __getattribute__
    off, tp = get_obj_offset(types, [self.name, attr])
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\object.py", line 154, in get_obj_offset
    elif not types.has_key(current_type):
AttributeError: 'dict' object has no attribute 'has_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lazagne.py", line 234, in <module>
    for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
  File "lazagne.py", line 87, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\config\run.py", line 169, in run_lazagne
    constant.system_dpapi = SystemDpapi()
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\config\dpapi_structure.py", line 165, in __init__
    LSASecrets().run()
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\lsa_secrets.py", line 25, in run
    secrets = get_file_secrets(constant.hives['system'], constant.hives['security'], is_vista_or_higher)
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 185, in get_file_secrets
    return get_secrets(sysaddr, secaddr, vista)
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 146, in get_secrets
    bootkey = get_bootkey(sysaddr)
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 112, in get_bootkey
    cs = find_control_set(sysaddr)
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in find_control_set
    csselect = open_key(root, ["Select"])
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\win32\rawreg.py", line 40, in open_key
    for s in subkeys(root):
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\win32\rawreg.py", line 50, in subkeys
    sk = (key.SubKeyLists[k]/["pointer", ["_CM_KEY_INDEX"]]).value
  File "C:\Users\mohammad      t\Downloads\LaZagne-master\Windows\lazagne\softwares\windows\creddump7\newobj.py", line 88, in __getattribute__
    raise AttributeError("'%s' has no attribute '%s'" % (self.name, attr))
AttributeError: '_CM_KEY_NODE' has no attribute 'SubKeyLists'

C:\Users\mohammad      t\Downloads\LaZagne-master\Windows>

**Comment by byehack** [comment]
it solved.
you can use `python3 branch` of lazagne project now
