### ISSUE TITLE
Lazagne can't find any browser passwords

### ISSUE THREAD

**Issue by ajndajndajndajn** [AlessandroZ/LaZagne#369]
Lazagne can't find any stored passwords for browsers even though they are available.

Here is the output after running it in verbose mode:

 ------------------- Firefox passwords -----------------

[!] No passwords found
 ------------------- Comodo icedragon passwords -----------------

[!] No passwords found
 ------------------- Icecat passwords -----------------

[!] No passwords found
 ------------------- Blackhawk passwords -----------------

[!] No passwords found
 ------------------- Cyberfox passwords -----------------

[!] No passwords found
 ------------------- K-meleon passwords -----------------

[!] No passwords found
 ------------------- Vivaldi passwords -----------------

[!] No passwords found
 ------------------- Brave passwords -----------------

[!] No passwords found
 ------------------- Torch passwords -----------------

[!] No passwords found
 ------------------- Comodo dragon passwords -----------------

[!] No passwords found
 ------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\haroo\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: c:\users\haroo\appdata\local\temp\fbppmhqta
[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704669EB

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07046692A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070466CBA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070466BCA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070466B3A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070466B6A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070466A7A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070466E0A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704732E0

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704738BA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047355A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047331A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047379A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704736A8

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047313A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047334A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704736DA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070473370

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070473160

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070473190

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047322A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704733AA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704733D0

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047358E

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704735BB

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047388B

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704731F8

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704731CB

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704732B8

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070473858

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047325E

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047328E

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047340A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047373E

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047346B

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047349B

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047343F

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047376B

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704734CF

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070473708

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704734FE

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047352A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047361B

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047364A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070473678

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704737CA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047382A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704737FA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704735EA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B0704781EA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070477D68

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B07047806A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070477CDA

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070477B50

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070477F7A

[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000002B070477EEA

[!] No passwords found
 ------------------- Coccoc passwords -----------------

[!] No passwords found
 ------------------- Chromium passwords -----------------

[!] No passwords found
 ------------------- 7star passwords -----------------

[!] No passwords found
 ------------------- Amigo passwords -----------------

[!] No passwords found
 ------------------- Elements browser passwords -----------------

[!] No passwords found
 ------------------- Uc browser passwords -----------------

[!] No passwords found
 ------------------- Ie passwords -----------------

[!] Internet Explorer passwords are stored in Vault (check vault module)
[!] No passwords found
 ------------------- Sputnik passwords -----------------

[!] No passwords found
 ------------------- Chedot passwords -----------------

[!] No passwords found
 ------------------- Chrome canary passwords -----------------

[!] No passwords found
 ------------------- Yandexbrowser passwords -----------------

[!] No passwords found
 ------------------- Orbitum passwords -----------------

[!] No passwords found
 ------------------- Uran passwords -----------------

[!] No passwords found
 ------------------- Opera passwords -----------------

[!] No passwords found
 ------------------- Kometa passwords -----------------

[!] No passwords found
 ------------------- Centbrowser passwords -----------------

[!] No passwords found
 ------------------- Epic privacy browser passwords -----------------

[!] No passwords found

[+] 0 passwords have been found.

elapsed time = 0.299000024796

**Comment by 0E800** [comment]
Do you have any browsers open when running?

Are you running it with elevated privs?

**Comment by AlessandroZ** [comment]
@ajndajndajndajn, I need more information. 
System arch (x86, x64) ? /  lazagne info (x86, x64) / Are you using python code or the executable ? 
Elevated priv or not ? etc.

I need the entire output? 

Try using same process and system arch.
