### ISSUE TITLE
Mozilla: KeyError: 'password-check'

### ISSUE THREAD

**Issue by littleyoda** [AlessandroZ/LaZagne#38]
Ubuntu 15.04:

```
./LaZagne-64bits mails -v

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

------------------- Thunderbird passwords -----------------

Profile path found: /home/<removed>/.thunderbird/<removed>.default

Traceback (most recent call last):
  File "<string>", line 191, in <module>
  File "<string>", line 107, in runModule
  File "<string>", line 75, in launch_module
  File "/home/joe/Desktop/build/LaZagne/out00-PYZ.pyz/softwares.browsers.mozilla", line 477, in run
  File "/home/joe/Desktop/build/LaZagne/out00-PYZ.pyz/softwares.browsers.mozilla", line 329, in is_masterpassword_correct
KeyError: 'password-check'

```

**Comment by AlessandroZ** [comment]
Could you try the version 0.9.1 please. I fix it.

**Comment by littleyoda** [comment]
works.
