### ISSUE TITLE
Opera: Input strings must be a multiple of 8 in length

### ISSUE THREAD

**Issue by markus80** [AlessandroZ/LaZagne#39]
Error occurs when "laZagne browsers" is called (version 0.9.1):

Traceback (most recent call last):
  File "<string>", line 190, in <module>
  File "<string>", line 106, in runModule
  File "<string>", line 75, in launch_module
  File "C:\Users\John\Desktop\build\laZagne\out00-PYZ.pyz\softwares.browsers.opera", line 45, in run
  File "C:\Users\John\Desktop\build\laZagne\out00-PYZ.pyz\softwares.browsers.opera", line 117, in decipher_old_version
  File "C:\Users\John\Desktop\build\laZagne\out00-PYZ.pyz\Crypto.Cipher.blockalgo", line 295, in decrypt
ValueError: Input strings must be a multiple of 8 in length

btw: Opera is "uninstalled".
Opera seems to be tried first. After this error output the program ends without doing other browsers.
OS: Windows 7 SP1 (x64, german)

**Comment by AlessandroZ** [comment]
It has been fix on the version 1.0.
