### ISSUE TITLE
Compiling on windows with other compiler

### ISSUE THREAD

**Issue by nickrh75** [AlessandroZ/LaZagne#397]
Not really an issue, since it compiles perfectly with pyinstaller.
But I would like to compile with another compiler… 
since .spec is specific to pyinstaller, am running the compiling command on lazagne.py. It compiles without errors, but when I try to run the .exe get the following traceback:

```
C:\Users\IEUser\Desktop\win10\lazagne\LaZagne-2.4\Windows\lazagne.dist>lazagne.exe
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\win10\lazagne\LAZAGN~1.4\Windows\LAZAGN~1.DIS\lazagne.py", line 18, in <module>
  File "C:\Users\IEUser\Desktop\win10\lazagne\LAZAGN~1.4\Windows\LAZAGN~1.DIS\lazagne\config\write_output.py", line 12, in <module lazagne.config.write_output>
  File "C:\Users\IEUser\Desktop\win10\lazagne\LAZAGN~1.4\Windows\LAZAGN~1.DIS\lazagne\config\constant.py", line 12, in <module lazagne.config.constant>
  File "C:\Users\IEUser\Desktop\win10\lazagne\LAZAGN~1.4\Windows\LAZAGN~1.DIS\lazagne\config\constant.py", line 46, in constant
  File "C:\Users\IEUser\Desktop\win10\lazagne\LAZAGN~1.4\Windows\LAZAGN~1.DIS\random.py", line 244, in randint
  File "C:\Users\IEUser\Desktop\win10\lazagne\LAZAGN~1.4\Windows\LAZAGN~1.DIS\random.py", line 216, in randrange
SystemError: ..\Objects\dictobject.c:833: bad argument to internal function
```
Any help deeply appreciated.

**Comment by AlessandroZ** [comment]
I have let opened the issue to see if someone could help you. I don't have the solution, but I would be interested to see if you got the answer. 

Have a nice day.
