### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by moaeddy** [AlessandroZ/LaZagne#398]
Traceback (most recent call last):
  File "Windows\laZagne.py", line 19, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\lazagne\config\manage_modules.py", line 4, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "Windows\lazagne\softwares\browsers\mozilla.py", line 15, in <module>
ImportError: No module named pyasn1.codec.der
[6372] Failed to execute script laZagne

**Comment by AlessandroZ** [comment]
Install requirements, check wiki
