### ISSUE TITLE
Problems with V 2.4.2

### ISSUE THREAD

**Issue by jmaravi** [AlessandroZ/LaZagne#406]
Ran Lazagne.exe provided in V 2.4.2 and getting the following errors (Running Lazagne under  nt authority\system):
C:\Windows\Temp>lazagne.exe all
lazagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[10764] Failed to execute script laZagne
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 169, in run_lazagne
  File "lazagne\config\dpapi_structure.py", line 165, in __init__
  File "lazagne\softwares\windows\lsa_secrets.py", line 25, in run
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 185, in get_file_secrets
  File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 146, in get_secrets
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 112, in get_bootkey
  File "lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in find_control_set
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 40, in open_key
  File "lazagne\softwares\windows\creddump7\win32\rawreg.py", line 52, in subkeys
  File "lazagne\softwares\windows\creddump7\newobj.py", line 107, in __getattribute__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by Hariz0n** [comment]
The same problem

**Comment by byehack** [comment]
new version is 2.4.3

**Comment by byehack** [comment]
fixed in the last commit. you can close this issue!
