### ISSUE TITLE
Build Error on execute

### ISSUE THREAD

**Issue by moaeddy** [AlessandroZ/LaZagne#407]
got this error when execute built BIN

Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\config\manage_modules.py", line 4, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\browsers\mozilla.py", line 15, in <module>
ImportError: No module named pyasn1.codec.der
[16512] Failed to execute script laZagne

Also, how do i change icon on BIN i tried check through folders but no icon were found and also, how do i add Version info as no version info included in source

**Comment by kanna27** [comment]
Try properly Anything else our update will soon

**Comment by AlessandroZ** [comment]
You should take some time to read the stacktace, it's written in front of you. 
`ImportError: No module named pyasn1.codec.der`

Install [requirements](https://github.com/AlessandroZ/LaZagne/blob/master/requirements.txt#L3)

**Comment by moaeddy** [comment]
i have seen where i made the mistake, but issue now is after built instead CMD display output of lazagne recoveries. it just run as normal file and disappear
