### ISSUE TITLE
Chrome on Linux

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#419]
Using the latest git code with `-vv`.

`Python 2.7.16 on Linux x86_64: x86_64` gives the following error in the Chrome section:
```
 ------------------- Chrome passwords -----------------

[!] Traceback (most recent call last):
  File "/home/moshepupik/git/LaZagne/Linux/lazagne/config/run.py", line 48, in run_module
    constant.st.print_output(i.capitalize(), pwd_found)  # Print the results
  File "/home/moshepupik/git/LaZagne/Linux/lazagne/config/write_output.py", line 146, in print_output
    pwd_found = [dict(t) for t in set([tuple(d.items()) for d in pwd_found])]
TypeError: writable buffers are not hashable
```
`Python 3.7.3 on Linux x86_64: x86_64` gives no output at all (not even the usual `[!] No passwords found`).

**Comment by plonibarploni** [comment]
What's actually happening is that there are no saved passwords stored, in fact the stored URLs are for sites which are set to NOT save passwords.

When I print out the entire dict to see what's inside, the output looks like this:
```
[{'URL': u'https://www.example.com/', 'Login': u'', 'Password': <read-write buffer ptr 0x7ff3e9dcf6f0, size 0 at 0x7ff3e9dcf6b0>}, {'URL': u'https://www.example.com/', 'Login': u'', 'Password': <read-write buffer ptr 0x7ff3e9dcf6b0, size 0 at 0x7ff3e9dcf670>}]
```
There's no check to make sure the data is valid before passing it back as `pwd_found`.
