### ISSUE TITLE
laZagne.py latest git..should I install or uninstall pypykatz ?

### ISSUE THREAD

**Issue by Papotito123** [AlessandroZ/LaZagne#478]
Hello:
@AlessandroZ ,laZagne.py latest git..should I install or uninstall pypykatz ? 
In requirements.txt I see there's no pypykatz but pycryptodome .

So,I uninstalled pypykatz and pycryptodome before running lazagne.py requirements.txt

I got plenty of errors in pypykatz wdgest  ,Chrome passwords.

 ------------------- Pypykatz passwords -----------------

[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\windows\ppypykatz.py", line 28, in run
    mimi = pypykatz.go_live()
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\pypykatz.py", line 51, in go_live
    mimi.start()
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\pypykatz.py", line 131, in start
    self.lsa_decryptor = self.get_lsa()
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\pypykatz.py", line 75, in get_lsa
    lsa_dec = LsaDecryptor(self.reader, lsa_dec_template, self.sysinfo)
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\lsadecryptor\lsa_decryptor.py", line 23, in __init__
    self.acquire_crypto_material()
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\lsadecryptor\lsa_decryptor.py", line 32, in acquire_crypto_material
    self.des_key = self.get_des_key(sigpos)
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\lsadecryptor\lsa_decryptor.py", line 37, in get_des_key
    return self.get_key(pos, self.decryptor_template.key_pattern.offset_to_DES_key_ptr)
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\lsadecryptor\lsa_decryptor.py", line 67, in get_key
    ptr_key = self.reader.get_ptr(ptr_key)
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\commons\readers\local\live_reader.py", line 276, in get_ptr
    return self.read_uint()
  File "C:\laza\Windows\lazagne\config\lib\pypykatz\commons\readers\local\live_reader.py", line 229, in read_uint
    return struct.unpack("<Q", self.read(8))[0]
struct.error: unpack requires a buffer of 8 bytes

[!] No passwords found

 ------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\TESTACCOUNT\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: C:\Users\TESTAC~1\AppData\Local\Temp\svvzxrkuj
[-] TESTACCOUNT not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
    --and so on ---
[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 140, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 629, in Win32CryptUnprotectData
    raise ValueError('MasterKeys not found')
ValueError: MasterKeys not found

Any shed of light much be appreciated.
Thanks.

**Comment by AlessandroZ** [comment]
It's really difficult for me to understand these problems because it worked for me. 

I have removed the embedded version and now everyone could use what version they want which mine is recommended for python 2.7 and the original one for python 3: https://github.com/AlessandroZ/LaZagne/blob/master/requirements.txt#L6:L7

**Comment by Papotito123** [comment]
Hello;
@AlessandroZ , just as info , your latest laZagne.py requierements.txt modification(git code revert pypykatz commits) worked good:

 ------------------- Pypykatz passwords -----------------

None
[+] Password found !!!
Type: wdigest_creds
Domain: DESKTOP-2GHHNFK
Password: zzzzzzzzzzzzz
Shahash: qqqqqqqqqqqqq
Nthash: qwqwqwqwqwqwqwqwq
Login: TESTACCOUNT

[+] Password found !!!
Type: credman_creds
Domain: DESKTOP-WINVIRT
Password: xxxxxxxxx
Login: testuser

 ------------------- Mscache passwords -----------------

Thanks/

**Comment by AlessandroZ** [comment]
Thanks for your feedback.

**Comment by MyLoginOnGitHub** [comment]
That's great!! Does it means that now pypykatz works good on python2 and python3?

**Comment by AlessandroZ** [comment]
In my test it worked for both version. :+1:

**Comment by MyLoginOnGitHub** [comment]
Bravo!
