### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by awpsn** [AlessandroZ/LaZagne#504]
Can i know how to compile  this program. Because i can't understand it. Please help me......

**Comment by CyberdyneSM101** [comment]
sure mate just download the .zip extract it , go to the folder that matches your operating system , windows for example you will see lazagne.py , open cmd in that directory and do ~ pyinstaller --onefile --console lazagne.py , if you don't have pyinstaller install it via pip , or you could simply download the compiled version from the release : https://github.com/AlessandroZ/LaZagne/releases/download/2.4.3/lazagne.exe

**Comment by AlessandroZ** [comment]
Please, check all older issues as well

**Comment by awpsn** [comment]
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Users\user\Desktop\LaZagne-2.4.3\Windows\laZagne.spec", line 30, in <module>
    coll = COLLECT(exe,
  File "c:\python38\lib\site-packages\PyInstaller\building\api.py", line 698, in __init__
    self.__postinit__()
  File "c:\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\python38\lib\site-packages\PyInstaller\building\api.py", line 742, in assemble
    shutil.copy(fnm, tofnm)
  File "c:\python38\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\Desktop\\LaZagne-2.4.3\\Windows\\build\\laZagne\\laZagne.exe'

**Comment by awpsn** [comment]
C:\Users\user\Desktop\LaZagne-2.4.3\Windows>C:\Python38\Scripts\pyinstaller.exe laZagne.py
1941 INFO: PyInstaller: 3.6
1941 INFO: Python: 3.8.3
1942 INFO: Platform: Windows-10-10.0.18362-SP0
1942 INFO: wrote C:\Users\user\Desktop\LaZagne-2.4.3\Windows\laZagne.spec
1944 INFO: UPX is not available.
1951 INFO: Extending PYTHONPATH with paths
['C:\\Users\\user\\Desktop\\LaZagne-2.4.3\\Windows',
 'C:\\Users\\user\\Desktop\\LaZagne-2.4.3\\Windows']
1951 INFO: checking Analysis
1952 INFO: Building Analysis because Analysis-00.toc is non existent
1952 INFO: Initializing module dependency graph...
1987 INFO: Caching module graph hooks...
2212 INFO: Analyzing base_library.zip ...
8473 INFO: Processing pre-find module path hook   distutils
8501 INFO: distutils: retargeting to non-venv dir 'c:\\python38\\lib'
17904 INFO: Caching module dependency graph...
18039 INFO: running Analysis Analysis-00.toc
18056 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python38\python.exe
18300 INFO: Analyzing C:\Users\user\Desktop\LaZagne-2.4.3\Windows\laZagne.py
21337 INFO: Processing module hooks...
21337 INFO: Loading module hook "hook-distutils.py"...
21447 INFO: Loading module hook "hook-encodings.py"...
21566 INFO: Loading module hook "hook-lib2to3.py"...
22316 INFO: Loading module hook "hook-pydoc.py"...
22383 INFO: Loading module hook "hook-sqlite3.py"...
23046 INFO: Loading module hook "hook-sysconfig.py"...
23064 INFO: Loading module hook "hook-xml.dom.domreg.py"...
23128 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
23138 INFO: Loading module hook "hook-xml.py"...
23139 INFO: Loading module hook "hook-_tkinter.py"...
24386 INFO: checking Tree
24386 INFO: Building Tree because Tree-00.toc is non existent
24387 INFO: Building Tree Tree-00.toc
25138 INFO: checking Tree
25138 INFO: Building Tree because Tree-01.toc is non existent
25139 INFO: Building Tree Tree-01.toc
25245 INFO: Looking for ctypes DLLs
25320 INFO: Analyzing run-time hooks ...
25325 INFO: Including run-time hook 'pyi_rth__tkinter.py'
25391 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
25422 INFO: Looking for dynamic libraries
26296 INFO: Looking for eggs
26297 INFO: Using Python library c:\python38\python38.dll
26298 INFO: Found binding redirects:
[]
26305 INFO: Warnings written to C:\Users\user\Desktop\LaZagne-2.4.3\Windows\build\laZagne\warn-laZagne.txt
26373 INFO: Graph cross-reference written to C:\Users\user\Desktop\LaZagne-2.4.3\Windows\build\laZagne\xref-laZagne.html
26454 INFO: checking PYZ
26454 INFO: Building PYZ because PYZ-00.toc is non existent
26455 INFO: Building PYZ (ZlibArchive) C:\Users\user\Desktop\LaZagne-2.4.3\Windows\build\laZagne\PYZ-00.pyz
27199 INFO: Building PYZ (ZlibArchive) C:\Users\user\Desktop\LaZagne-2.4.3\Windows\build\laZagne\PYZ-00.pyz completed successfully.
27243 INFO: checking PKG
27244 INFO: Building PKG because PKG-00.toc is non existent
27245 INFO: Building PKG (CArchive) PKG-00.pkg
27374 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
27377 INFO: Bootloader c:\python38\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
27377 INFO: checking EXE
27378 INFO: Building EXE because EXE-00.toc is non existent
27379 INFO: Building EXE from EXE-00.toc
27409 INFO: Appending archive to EXE C:\Users\user\Desktop\LaZagne-2.4.3\Windows\build\laZagne\laZagne.exe
27832 INFO: Building EXE from EXE-00.toc completed successfully.
27836 INFO: checking COLLECT
27836 INFO: Building COLLECT because COLLECT-00.toc is non existent
27843 INFO: Building COLLECT COLLECT-00.toc
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python38\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Users\user\Desktop\LaZagne-2.4.3\Windows\laZagne.spec", line 30, in <module>
    coll = COLLECT(exe,
  File "c:\python38\lib\site-packages\PyInstaller\building\api.py", line 698, in __init__
    self.__postinit__()
  File "c:\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\python38\lib\site-packages\PyInstaller\building\api.py", line 742, in assemble
    shutil.copy(fnm, tofnm)
  File "c:\python38\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\Desktop\\LaZagne-2.4.3\\Windows\\build\\laZagne\\laZagne.exe'

**Comment by awpsn** [comment]
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
    from lazagne.config.manage_modules import get_categories
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lazagne\config\manage_modules.py", line 4, in <module>
    from lazagne.softwares.browsers.mozilla import firefox_browsers
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lazagne\softwares\browsers\mozilla.py", line 15, in <module>
    from pyasn1.codec.der import decoder
ModuleNotFoundError: No module named 'pyasn1'
[6744] Failed to execute script laZagne

**Comment by Banaanhangwagen** [comment]
Double check if there are no errors when using ´pyinstaller --onefile`

**Comment by AlessandroZ** [comment]
Read: https://github.com/AlessandroZ/LaZagne/issues/507#issuecomment-641658983
and the wiki: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile

You're missing some windows dependencies.
