### ISSUE TITLE
Error while running on Windows

### ISSUE THREAD

**Issue by codeayra** [AlessandroZ/LaZagne#515]
I am running the latest code using

python laZagne.py browsers
and I am getting following error

Traceback (most recent call last):
  File "laZagne.py", line 21, in <module>
    from lazagne.config.run import run_lazagne, create_module_dic
  File "E:\pacl\LaZagne-master\Windows\lazagne\config\run.py", line 10, in <module>
    from lazagne.config.dpapi_structure import SystemDpapi, are_masterkeys_retrieved
  File "E:\pacl\LaZagne-master\Windows\lazagne\config\dpapi_structure.py", line 6, in <module>
    from lazagne.config.DPAPI.masterkey import MasterKeyPool
  File "E:\pacl\LaZagne-master\Windows\lazagne\config\DPAPI\masterkey.py", line 382
    yield u'masterkey {masterkey} decrypted using credhists key'.format(
SyntaxError: 'return' with argument inside generator

**Comment by AlessandroZ** [comment]
Should be fixed now.
