### ISSUE TITLE
lazagne 32e181f fix chromium bug ,,,

### ISSUE THREAD

**Issue by Papotito123** [AlessandroZ/LaZagne#528]
Hello:
wdigest is not Enabled.
I tested this lazagne fix chromium bug (32e181f ) and gives this error not related to chromium:

---------------- Windows passwords -----------------

[!] Traceback (most recent call last):
  File "C:\lozogno\Windows\lazagne\config\run.py", line 45, in run_module
    pwd_found = module.run()  # run the module
  File "C:\lozogno\Windows\lazagne\softwares\windows\windows.py", line 50, in run
    password = constant.user_dpapi.get_cleartext_password()
  File "C:\lozogno\Windows\lazagne\config\dpapi_structure.py", line 149, in get_cleartext_password
    return self.umkp.get_cleartext_password()
  File "C:\lozogno\Windows\lazagne\config\DPAPI\masterkey.py", line 326, in get_cleartext_password
    guid = self.get_preferred_guid()
  File "C:\lozogno\Windows\lazagne\config\DPAPI\masterkey.py", line 315, in get_preferred_guid
    format(GUID2[1], '08x'), format(GUID2[2], '04x'))
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'

Thanks.

**Comment by Papotito123** [comment]
Hello:
Just close.
