### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by Pyth79** [AlessandroZ/LaZagne#544]
Hello,
I ran this program on another computer without any problem, but here i get this error
Traceback (most recent call last):
  File "C:\Users\**\LaZagne-master\Windows\laZagne.py", line 19, in <module>
    from lazagne.config.manage_modules import get_categories
  File "C:\Users\**\LaZagne-master\Windows\lazagne\config\manage_modules.py", line 4, in <module>
    from lazagne.softwares.browsers.mozilla import firefox_browsers
  File "C:\Users\**\LaZagne-master\Windows\lazagne\softwares\browsers\mozilla.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
I have the requirements installed and I'm running Python 3.9.1
Any idea ?

**Comment by Papotito123** [comment]
Hello:
Maybe this Mozilla has a Master Password?

**Comment by Pyth79** [comment]
> Hello:
> Maybe this Mozilla has a Master Password?

I don't have mozilla firefox on my other computer, and not on this one either. I don't think it's the problem

**Comment by Papotito123** [comment]
Hello
I run laZagne.py all -vvv in Win 1909 x64 and Win 20H1 x64 and always mark some errors in Mozilla even I have it in both OS.
But lazagne run and show the logins for Firefox and other.

**Comment by FloatKey** [comment]
On first lines in mozilla.py file, you have the imports lines (for the 7, "json" apparently), some dependencies maybe not properly installed, run the requirements.txt file and try to re-install the json module for python and retry.

> pip install jsonlib
> pip install -r /[path to]/requirements.txt

It should work.
