### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Krytical13** [AlessandroZ/LaZagne#55]
Microsoft Windows Version 6.0.6002 Server 2008 SP2 Standard x64

laZagne --version
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\Users\tuquo\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_importers.py", line 276, in load_module
  File "C:\Users\tuquo\Desktop\LaZagne\build\LaZagne\out00-PYZ.pyz\config.manageModules", line 3, in <module>
  File "C:\Users\tuquo\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_importers.py", line 276, in load_module
  File "C:\Users\tuquo\Desktop\LaZagne\build\LaZagne\out00-PYZ.pyz\softwares.browsers.chrome", line 3, in <module>
  File "C:\Users\tuquo\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_importers.py", line 420, in load_module
ImportError: DLL load failed: The specified module could not be found.

**Comment by AlessandroZ** [comment]
I fixed this issue for many windows version. I see that some still have it. I have to import some specific DLL when I build the executable file. 
I don't know which one is missing for you. I will take a look when I will have some time.
