### ISSUE TITLE
Getting error on Win7 32bit

### ISSUE THREAD

**Issue by bigbossidr** [AlessandroZ/LaZagne#59]
I call the executable with parameter with "all" parameter, but getting the following error:

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "<string>", line 190, in <module>
  File "<string>", line 116, in runAllModules
  File "<string>", line 75, in launch_module
  File "C:\Users\tuquo\Desktop\LaZagne\build\LaZagne\out00-PYZ.pyz\softwares.browsers.mozilla", line 439, in run
  File "C:\Users\tuquo\Desktop\LaZagne\build\LaZagne\out00-PYZ.pyz\softwares.browsers.mozilla", line 119, in get_path
TypeError: print_debug() takes exactly 2 arguments (1 given)

**Comment by AlessandroZ** [comment]
Fix in version 1.3.
