### ISSUE TITLE
Lazagne Error (executable) on Windows! enconding error

### ISSUE THREAD

**Issue by yrifl** [AlessandroZ/LaZagne#590]
```
u'\n|====================================================================|\n|                                                                    |\n|                        The LaZagne Project                         |\n|                                                                    |\n|                          ! BANG BANG !                             |\n|
                                                     |\n|====================================================================|\n'
u'\n########## User: faiq ##########\n'
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 136
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 139
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 136
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 139
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 136
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 139
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 136
Traceback (most recent call last):
  File "logging\__init__.py", line 879, in emit
LookupError: unknown encoding: cp65001
Logged from file write_output.py, line 139
u'\n[+] 0 passwords have been found.\n\nelapsed time = 0.0159997940063'

```
I found this really weird, is there any solution to solve? please update

**Comment by HGStyle** [comment]
its because python cannot decode "cp65001" encoding.
try to update python (i recommend the last version, python 3.11)
https://python.org/
