### ISSUE TITLE
i have a problem, can anybody help me?

### ISSUE THREAD

**Issue by cesc08** [AlessandroZ/LaZagne#591]
Traceback (most recent call last):
  File "laZagne.py", line 233, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 169, in run_lazagne
  File "lazagne\config\dpapi_structure.py", line 172, in __init__
  File "lazagne\config\DPAPI\masterkey.py", line 434, in try_system_credential
AttributeError: 'NoneType' object has no attribute 'decrypt_with_key'
[18620] Failed to execute script laZagne

**Comment by AlessandroZ** [comment]
Should be fixed now: https://github.com/AlessandroZ/LaZagne/pull/603
