### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Inetgeek** [AlessandroZ/LaZagne#598]
#### The code error is as follows：
------------------------------------------------------------------------
```
Traceback (most recent call last):
  File "laZagne.py", line 233, in <module>
    for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
  File "laZagne.py", line 87, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
  File "C:\Users\xxx\Desktop\LaZagne-master\LaZagne-master\Windows\lazagne\config\run.py", line 197, in run_lazagne
    for r in run_category(category_selected, subcategories):
  File "C:\Users\xxx\Desktop\LaZagne-master\LaZagne-master\Windows\lazagne\config\run.py", line 118, in run_category
    if are_masterkeys_retrieved():
  File "C:\Users\xxx\Desktop\LaZagne-master\LaZagne-master\Windows\lazagne\config\dpapi_structure.py", line 33, in are_masterkeys_retrieved
    constant.user_dpapi.check_credentials([constant.username] + constant.password_found)
  File "C:\Users\xxx\Desktop\LaZagne-master\LaZagne-master\Windows\lazagne\config\dpapi_structure.py", line 92, in check_credentials
    for ok, r in self.umkp.try_credential(sid=self.sid, password=password):
  File "C:\Users\xxx\Desktop\LaZagne-master\LaZagne-master\Windows\lazagne\config\DPAPI\masterkey.py", line 375, in try_credential
    self.credhists[sid].decrypt_with_password(password)
  File "C:\Users\xxx\Desktop\LaZagne-master\LaZagne-master\Windows\lazagne\config\DPAPI\credhist.py", line 142, in decrypt_with_password
    self.decrypt_with_hash(hashlib.sha1(password.encode("UTF-16LE")).digest())
AttributeError: 'bytes' object has no attribute 'encode'
```
-------------------------------------------------------------------------
**hoping that the author will fix this bug, thanks!**
-------------------------------------------------------------------------
## add
The information obtained under Windows is incomplete and the URL will be lost. Moreover, the obtained password is not in plain text and needs to be decrypted. The format is as follows:
```
b"v10P\xa9'\x9a_\xf0\xcd...\x10\xb4H\xb5\...\xe9\x9e\n\xa0\xed\x82"
b'v10<\xe2\xf0\x1c\xc4c9}\xfav\x9en<\x8c\xc...xf4\.....\xa5Z6H2{MJ\xc9\x0c...\x12T\xbb'
b'v10bd}f\xcd:\xa9\.....KmmS\xe5...d\xaa\xf0%\x95\\OA\xaf\xa7=\...d9\xebF{'
...
```
This password encoding encryption comes from the Chrome Edge browser.

**Comment by AlessandroZ** [comment]
Should be fixed with this PR: https://github.com/AlessandroZ/LaZagne/pull/603
