### ISSUE TITLE
Linux version of LaZagne is crashing

### ISSUE THREAD

**Issue by HGStyle** [AlessandroZ/LaZagne#609]
Ok, so I tried to run LaZagne on my Linux computer, but:
```
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py chats

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py sysadmin

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py databases

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py mails

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py memory

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py wifi

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py browsers

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py wallet

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/laZagne.py", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
```
Every command i tried crashes (except the "all" one)
The "all" one crashes too, but its not the same error:
```
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ python3 laZagne.py all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[-] Traceback (most recent call last):
  File "/home/hg/Bureau/LaZagne-2.4.3/Linux/lazagne/softwares/wallet/libsecret.py", line 57, in run
    from jeepney.integrate.blocking import connect_and_authenticate
ModuleNotFoundError: No module named 'jeepney.integrate'

------------------- Filezilla passwords -----------------

[+] Password found !!!
[some passwords found in filezilla]
```
Can someone patch these bugs please ?
I used the last version and installed all the libaries (i did `python3 -m pip install -r requirements.txt`)
I re-checked and the libary `jeepney` is really installed:
```
hg@mxlinux-toshiba:~/Bureau/LaZagne-2.4.3/Linux
$ pip3 install jeepney
Requirement already satisfied: jeepney in /home/hg/.local/lib/python3.9/site-packages (0.8.0)
```
I think this version was never tested because Linux is not used by a lot of persons.

**Comment by HGStyle** [comment]
Edit: I just re-downloaded the latest code (not from the releases) and its now working.
