### ISSUE TITLE
AttributeError: 'Mozilla' object has no attribute 'getLoginData'

### ISSUE THREAD

**Issue by thomasleplus** [AlessandroZ/LaZagne#658]
Hi,

I am trying to switch from firepwd to LaZagne as it seems more versatile but I am facing the following error. I have cloned the repo and I am running the following command from the `Mac` subdirectory:

```
$ python3 laZagne.py browsers -firefox -oJ -password '*****' -vv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 3.9.6 on Darwin arm64: arm

 ------------------- Firefox passwords -----------------

[!] Profile path found: /Users/*****/Library/Application Support/Firefox/Profiles/*****.default-release
[!] Traceback (most recent call last):
  File "/Users/*****/code/LaZagne/Mac/lazagne/config/run.py", line 69, in run_module
    pwd_found = module[i].run()  # run the module
  File "/Users/*****/code/LaZagne/Mac/lazagne/softwares/browsers/mozilla.py", line 526, in run
    credentials = self.getLoginData(profile)
AttributeError: 'Mozilla' object has no attribute 'getLoginData'

[+] File written: ./credentials_13122024_144056.json

[+] 0 passwords have been found.

elapsed time = 0.004775047302246094
```

I have run `pip3 install -r requirements.txt` as per the README instructions. I probably just missed something else but can't put my finger on it.

Cheers

**Comment by thomasleplus** [comment]
FYI I checked out master and now I am getting the following error:

```
File "/Users/thomas/code/LaZagne/Mac/lazagne/softwares/browsers/mozilla.py", line 388, in get_login_data c.execute('SELECT * FROM moz_logins;')
sqlite3.OperationalError: no such table: moz_logins
```

Cheers
