### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Omardavinci** [AlessandroZ/LaZagne#77]
When i compile show me this error
Traceback (most recent call last):
  File "C:\Users\moh\Desktop\LaZagne-master\Windows\laZagne.py", line 21, in <module>
    from lazagne.softwares.browsers.mozilla import Mozilla
  File "C:\Users\moh\Desktop\LaZagne-master\Windows\lazagne\softwares\browsers\mozilla.py", line 15, in <module>
    from pyasn1.codec.der import decoder
ImportError: No module named pyasn1.codec.der

When i try to compile opera alone ;( show me this
Traceback (most recent call last):
  File "papa.py", line 2, in <module>
    from Crypto.Cipher import DES3
ImportError: No module named Crypto.Cipher

I think because i need to include file to cypher pass
Thx for your project is awesome and incredible!

**Comment by AlessandroZ** [comment]
Have you installed all dependencies: https://github.com/AlessandroZ/LaZagne#requirements

Here is where you could get pyasn1: https://pypi.python.org/pypi/pyasn1/

**Comment by Dem0nKa** [comment]
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 197, in run_lazagne
  File "lazagne\config\users.py", line 57, in set_env_variables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 0: ordinal not in range(128)
[9944] Failed to execute script laZagne

Please help me.
